COLORS = {
    'window': '#1a1a1a',
    'window_text': '#f0f0f0',
    'base': '#161616',
    'alternate_base': '#242424',
    'tooltip': '#e0e0e0',
    'text': '#ffffff',
    'button': '#363636',
    'button_text': '#ffffff',
    'highlight': '#1177BB',             
    'highlight_hover': '#3399DD',       
    'highlight_pressed': '#0D5A8C',     
    'highlight_disabled': '#555F70',    
    'highlight_disabled_text': '#A0B0C0',
    'border': '#404040',
    'success': '#4CAF50',       
    'success_hover': '#66BB6A', 
    'success_pressed': '#388E3C',
    'success_disabled': '#7E9E7E',      
    'success_disabled_text': '#C0D0C0',
    'warning': '#FF9800',          
    'warning_hover': '#FFB74D',    
    'warning_pressed': '#F57C00',  
    'warning_disabled': '#AA6A33', 
    'warning_disabled_text': '#FFD7A5',
    'danger': '#D32F2F',              
    'danger_hover': '#E57373',        
    'danger_pressed': '#B71C1C',      
    'danger_disabled': '#8C5555',     
    'danger_disabled_text': '#D0A0A0',
    'disabled': '#666666',
    'accent': '#BB86FC',
    'secondary_accent': '#03DAC6',
    'selected_item': '#2E7D32',         # item seleccionado
    'selected_item_hover': '#388E3C',   # hover sobre item seleccionado
}